---
- name: OpenEyes Development Server
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.composer
    - MaximeThoonsen.php5-xdebug
    - pludoni.wkthmltox
    - app
